### ISSUE TITLE
Review request - Section Basic demo walkthrough

### ISSUE THREAD

**Issue by VidyashreeTarikereUgent** [VidyashreeTarikereUgent/todoApp-demoPaper#6]
https://github.com/VidyashreeTarikereUgent/todoApp-demoPaper/blob/master/content/basicDemoWalkthrough.md

**Comment by rubensworks** [comment]
Partial review in https://github.com/VidyashreeTarikereUgent/todoApp-demoPaper/tree/review/rt-1, but I did not continue, as there appear to be many todo's in the text still, so I'll wait until it's ready.

**Comment by j-steinbach** [comment]
https://github.com/VidyashreeTarikereUgent/todoApp-demoPaper/blob/review/jst-1/content/basicDemoWalkthrough.md

@rubensworks  It is ready, I just had a different approach to writing texts, as I don't have much experience with collaborating/reviewing. In general my TODOs act more as guideline notes and comments. But I removed all of them and tried converting my comments into a more 'sholarlyMarkdown' style :)

I don't know if this is 100% perfect, but I am sick and feel almost literally like dying, so this is the best I can currently do.

**Comment by rubensworks** [comment]
Done in https://github.com/VidyashreeTarikereUgent/todoApp-demoPaper/tree/review/rt-2
